USE [TIEMPOS_MUERTOS]
GO

/****** Object:  Table [MAGNA\p.rguerrero].[FALLOS_CALIDAD]    Script Date: 18/01/2018 12:04:39 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FALLOS_CALIDAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AMBIENTE] [numeric](1, 0) NULL,
	[TIPO_FALLA] [varchar](15) NULL,
	[MODO_FALLA] [varchar](50) NULL,
	[CAUSA_FALLA] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


